spring:
  application:
    name: techmaps-application
  datasource:
    url: jdbc:postgresql://localhost:5432/techmaps
    username: techmaps-app
    password: techmaps-app
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialetc: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

queries:
  sql:
    dashboard-dao:
      insert:
        dashboard: >
      select:
        dashboard-by-id: >
          SELECT * FROM techmaps_platform.dashboard WHERE id = ?
    roadmap-dao:
      insert:
        roadmap: >
          INSERT INTO techmaps_platform.roadmap (id, title, type, status, lang, start_time, finish_time, commit_counter, dashboard_id) VALUES (?, ?, ?::techmaps_platform.roadmap_type, ?::techmaps_platform.roadmap_status, ?::techmaps_platform.roadmap_lang, ?, ?, ?, ?)
      select:
        roadmap-by-id: >
          SELECT id, title, type, status, lang, start_time, commit_counter, dashboard_id FROM techmaps_platform.roadmap WHERE id = ?
        roadmap-all: >
          SELECT * FROM techmaps_platform.roadmap
      update:
        roadmap: >
      exists:
        roadmap-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.roadmap WHERE id = ?)
    stage-dao:
      insert:
        stage: >
          INSERT INTO techmaps_platform.stage (id, roadmap_id, theme, status, commit_counter) VALUES (?, ?, ?::techmaps_platform.stage_theme, ?::techmaps_platform.stage_status, ?)
      select:
        stage-by-id: >
          SELECT * FROM techmaps_platform.stage WHERE id = ?
        stage-by-roadmap-id: >
            SELECT * FROM techmaps_platform.stage WHERE roadmap_id = ?
    task-dao:
      insert:
          task: >
            INSERT INTO techmaps_platform.task (id, name, description, status, created_at, updated_at, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)
      select:
        task-by-id: >
          SELECT * FROM techmaps_platform.task WHERE id = ?
        task-by-stage-id: >
          SELECT * FROM techmaps_platform.task WHERE stage_id = :userId
        task-all: >
          SELECT * FROM techmaps_platform.task
      update:
          task: >
      delete:
          task: >
      exists:
          task-by-id: >